/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'tw';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string, variables?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Translations Dictionary inspired by formal standard Ashanti Twi as shown on JW.org/tw
const dictionary: Record<Language, Record<string, string>> = {
  en: {
    // Header & Navigation
    'nav.home': 'Home Hub',
    'nav.municipality': 'Local Guide',
    'nav.municipality_menu': 'Local Guide Menu',
    'nav.auction': 'Deals Page',
    'nav.events': 'Community Events',
    'nav.health_safety': 'Safety Advisory',
    'nav.jobs': 'Offinso Careers',
    'nav.careers_menu': 'Offinso Careers Menu',
    'nav.literacy': 'Courses',
    'nav.jobs_sub': 'Job Openings',
    'nav.charity': 'Relief Programs',
    'nav.relief_menu': 'Relief Programs Menu',
    'nav.all_programs_overview': 'All Programs Overview',
    'nav.agric_sector': 'Agricultural Sector',
    'nav.social_dev': 'Social Development',
    'nav.travel': 'Travel Abroad',
    'header.banner_left': 'Offinso Resident Private Connection Hub, Ghana',
    'header.banner_right': 'Ashanti Region, West Africa',
    'header.seal_text': 'OFFINSO PRIVATE HUB',
    'header.bilingual_badge': 'EN / TWI',
    'header.title': 'OFFINSO PRIVATE HUB',
    'header.subtitle': 'Resident Created Private Connection Link',
    'header.search_placeholder': 'Search Offinso jobs, auctions, relief...',
    'header.river_status': 'River Offin Crossing:',
    'header.river_passable': 'PASSABLE',
    'header.weather': 'Offinso: 28°C Tropical',
    'header.hotline_prefix': '🔴 Offin Water Advisory: ',
    'header.warning_prefix': '⚡ Local Notice: stable water table',
    
    // Auth Buttons & Modal
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Log Out',
    'auth.welcome_user': 'Welcome, {name}',
    'auth.modal_title_login': 'Log In to Local Registry',
    'auth.modal_title_signup': 'Register Local Resident Account',
    'auth.username': 'Username (Email or Name)',
    'auth.password': 'Secret Pin / Password',
    'auth.no_account': "Don't have an account?",
    'auth.already_account': 'Already registered?',
    'auth.security_question': 'Local Verification Question',
    'auth.security_placeholder': 'Answer for identity reset...',
    'auth.secure_pet': 'What is the name of your childhood hometown in Offinso?',
    'auth.secure_parents': 'In what Ashanti community did your parents meet?',
    'auth.secure_school': 'What was your first primary school in Offinso?',
    'auth.secure_harvest': 'What was your first crop harvest yield rate?',
    
    // Common / Global
    'global.explore': 'Explore',
    'global.apply_now': 'Apply Now',
    'global.details': 'Details',
    'global.back': 'Back',
    'global.submit': 'Submit',
    'global.cancel': 'Cancel',
    'global.active': 'Active',
    'global.currency': 'GH₵',
    
    // Home Hub Page
    'home.welcome_link': 'Offinso Private Link',
    'home.akwaaba_title': 'Offinso Connection Man',
    'home.akwaaba_subtitle': 'Akwaaba — Welcome to Offinso Connection Hub',
    'home.hero_para': 'A fertile local hub of rich cocoa pastures, forest reserves, and cooperative trade. Created by an Offinso resident to connect job seekers with agriculture or commerce roles, coordinate private relief applications, arrange regional transport and tours, and host craft auctions for profit.',
    'home.see_bulletins': 'See Offinso Bulletins',
    'home.join_registry': 'Join Resident Registry',
    'home.municipal_services': 'Private Activities & Services',
    'home.select_hub_office': 'SELECT A LOCAL CONNECTION HUB BELOW',
    'home.bulletins_title': 'Offinso Bulletins & Local News',
    'home.courses_title': 'Available Academy Courses',
    'home.courses_subtitle': 'Educational campaigns, professional training & digital skill builders for local development.',
    'home.no_news': 'No news bulletins have been posted matching current filters.',
    'home.live_stats': 'Offinso Live Hub Stats',
    'home.road_advisory': 'Offin River & Roads Advisory',
    'home.road_para': 'River Offin Bridge passable for all transport categories. River water levels are stable after seasonal rainfalls near Abofour. All bypass trunk roads and secondary farmer routes are dry and safe.',
    'home.eco_tour_teaser': 'Visiting Amanchia Monkey Sanctuary',
    'home.eco_tour_para': 'Take an immersive walk along the protected primary rainforest paths. Spot traditional monkey squads in their wild, conserved habitats.',
    'home.eco_experience_label': 'Ecotourism Experience',
    'home.pop_label': 'Offinso Population',
    'home.bids_label': 'Active Auction Items',
    'home.jobs_label': 'Jobs Open / Filled',
    'home.relief_label': 'Relief Disbursed',
    
    // Benefactor Appreciation keys
    'home.appreciation_badge': 'BENEFACTOR PARTNER APPRECIATION',
    'home.appreciation_title': 'Heartfelt Gratitude to Haven Light Charity LBG',
    'home.appreciation_desc': 'We express our deepest appreciation to Haven Light Charity LBG for their immense and continued support of the Offinso Community Relief & Charity Grants. Through their dedicated administration and funding, numerous farming households, cooperatives, and local laborers receive critical seed subsidies, clean water access, work safety tutoring, and crucial micro-grants. Together, we are building a more resilient, safer, and self-sufficient Offinso.',
    'home.appreciation_twi': 'Aseda kɛseɛ kɔ Haven Light Charity LBG hɔ',
    
    // Auction Section
    'auction.floor_title': 'Community Auction Floor',
    'auction.municipal_office': 'Offinso Private Secretariat',
    'auction.floor_para': 'Reallocating historic items, artisanal wares, and traditional Ashanti antiques safely. Minimum increment of GH₵5.',
    'auction.stats_bidders': 'Active registered community bidders:',
    'auction.lot_count': 'Active items matching conditions:',
    'auction.price_filter': 'Price range constraint:',
    'auction.min_bid_label': 'Min Bid Price (GH₵)',
    'auction.max_bid_label': 'Max Bid Price (GH₵)',
    'auction.bidder_prompt': 'Enterprise Buyer (Resident Account Required)',
    'auction.become_bidder': 'Please register/login to place local bids.',
    'auction.bid_successful': 'Bid Placed Successfully!',
    'auction.bid_too_low': 'Your bid is too low. The minimum allowed bid is {min} (current bid + {inc} increment).',
    'auction.ends_in': 'ends in {time}',
    'auction.starting_bid': 'Starting Bid',
    'auction.current_leading': 'Current Leading',
    'auction.no_bids': '0 bids',
    'auction.bids_count': '{count} bids',
    'auction.is_high_bidder': 'You are the leading bidder!',
    'auction.outbid': 'You have been outbid!',
    'auction.place_bid_btn': 'Place Local Bid',
    'auction.rebid_btn': 'Re-Bid now ({amount}+)',
    'auction.submit_bid_btn': 'Confirm Security Bid',
    'auction.backing_rules_label': 'Registry Conditions',
    'auction.backing_rules_text': 'All community bids placed are contractually binding. Be prepared to pick up won items at House No. OP/24 Kokote, Near Methodist JHS inside Offinso, Ashanti.',
    'auction.your_bid_amount': 'Your Bid Amount (GH₵)',
    'auction.min_increment_hint': 'Minimum increment is GH₵ 5. Must be at least GH₵ {amount}.',
    'auction.gold_weight': 'Heritage Antiques',
    'auction.crafts': 'Ashanti Crafts',
    'auction.relics': 'Agricultural Relics',
    'auction.tools': 'Trade Tools',
    'auction.utensils': 'Culinary Utensils',
    'auction.fine_arts': 'Fine Arts',
    
    // Job Search Section
    'jobs.portal_title': 'Private Employment Ledger',
    'jobs.sub_office': 'Youth & Private Labor Bourse',
    'jobs.portal_para': 'Connecting resident labor pools with smallholders, cacao processors, and regional nature sanctuaries. Secure sustainable livelihoods.',
    'jobs.tab_listings': 'Browse Vacancies',
    'jobs.tab_applications': 'Resident Applications',
    'jobs.tab_post': 'Post a Local Job',
    'jobs.search_title': 'Search Job Listings',
    'jobs.select_category': 'Select Industrial Category',
    'jobs.select_type': 'Work Schedule',
    'jobs.salary_label': 'Salary Range / Month',
    'jobs.all_categories': 'All Industries',
    'jobs.salary_limit_label': 'Minimum Monthly Wage Filter',
    'jobs.post_vacancy_title': 'Establish Local Job Opening',
    'jobs.post_vacancy_para': 'List active positions to find capable Offinso farmers, weavers, drivers, or tech managers. All posts undergo resident moderator verification.',
    'jobs.form_title': 'Position Title',
    'jobs.form_employer': 'Employer Name / Cooperative',
    'jobs.form_location': 'Local Community (e.g., Anyinasuso, Abofour)',
    'jobs.form_salary': 'Expected Monthly Pay (GH₵)',
    'jobs.form_desc': 'Detailed Job Description',
    'jobs.form_req': 'Core Job Requirements (One key item per line)',
    'jobs.create_post_btn': 'Verify & Post Vacancy',
    'jobs.candidate_apply_title': 'Apply for Local Opening',
    'jobs.apply_fullName': 'Full Legal Name',
    'jobs.apply_phone': 'Mobile Phone (MoMo Registered Preferred)',
    'jobs.apply_experience': 'Work Experience & Relevant Skills',
    'jobs.apply_narrative': 'Short Narrative',
    'jobs.apply_narrative_placeholder': 'Why are you the right candidate to lift Offinso from the poverty line...',
    'jobs.apply_success': 'Application Submitted Successfully!',
    'jobs.tracker_code': 'Your application tracking reference is:',
    'jobs.requirements': 'Job Requirements',
    'jobs.your_applications': 'Your Logged Applications',
    'jobs.no_applications': 'You have not submitted any job proposals yet.',
    'jobs.applied_on': 'Applied on {date}',
    'jobs.status': 'Status: {status}',
    'jobs.verified_status': 'Verified Resident',
    
    // Charity Section
    'charity.alliance_title': 'Community Relief & Charity Grants',
    'charity.sub_office': 'Haven Light Charity LBG',
    'charity.alliance_para': 'Mitigating climate hurdles, smallholder farming shifts, and local startup costs for Offinso families below the poverty line. Administered by Haven Light Charity LBG.',
    'charity.tab_programs': 'Relief Funds',
    'charity.tab_apply': 'File Relief Claim',
    'charity.tab_track': 'Track My Grants',
    'charity.empowering': 'Empowering Local Communities',
    'charity.empowering_text': 'Administered by Haven Light Charity LBG, this Private Fund redirects 15% of all artisan auction proceeds directly into seed subsidies, water well drills, and rural women empowerment groups.',
    'charity.required_dossiers': 'Required Dossiers',
    'charity.required_dossiers_text': 'Generally, applying requires proof of residence in Offinso, documented household income brackets, and an assessment narrative detailing your emergency status.',
    'charity.fund_pool': 'Total relief disbursed to date:',
    'charity.claim_title': 'File a Community Relief Claim',
    'charity.claim_para': 'Submit structured claims for certified micro-grants. Approved bursaries are paid directly via mobile capital transfers.',
    'charity.claim_success': 'Social Benefit Claim Registered!',
    'charity.claim_ref': 'Reference Tracker Code',
    'charity.claim_success_msg': 'Your claim has been logged inside our ledger. Please record your reference code for tracking: {ref}',
    'charity.form_program': 'Select Target Fund Program',
    'charity.form_program_placeholder': '-- Select specialized program --',
    'charity.form_income': 'Gross Annual Income Level',
    'charity.form_desc': 'Assessment Narrative & Proof of Emergency',
    'charity.submit_claim_btn': 'Validate & Submit Claim',
    'charity.track_title': 'Track Relief Applications',
    'charity.track_para': 'Query your benefit application progress using your email address or unique tracking number.',
    'charity.track_btn': 'Query Progress',
    'charity.track_query_placeholder': 'e.g., kofi@offinso.com or OFS-RLF-189',
    'charity.no_records': 'No programs found matching {query}.',
    'charity.status_label': 'Resident Status',
    
    // Travel Section
    'travel.agency_title': 'NAY TRAVEL COMPANY',
    'travel.sub_office': 'International Travel & Visas Office',
    'travel.agency_para': 'All packages are offered by NAY TRAVEL COMPANY. We provide premier visa processing, travel assistance, and document vetting including bank drafts and invitation letters.',
    'travel.tab_packages': 'View Travel Packages',
    'travel.tab_my_trips': 'My Enquiries',
    'travel.calculator_title': 'Enquiry & Travel Quote Planner',
    'travel.calc_directions': 'Select a travel package on the left to start your custom enquiry.',
    'travel.destination_label': 'Target Destination / Country',
    'travel.destination_placeholder': 'e.g. Canada, UK, Europe',
    'travel.max_price': 'Max Price Limit (GH₵ {price} GHS)',
    'travel.price_range': 'Min: GH₵ 100 | Max: GH₵ 10000 GHS',
    'travel.base_rate': 'PROCESSING FEE',
    'travel.per_person': '/applicant',
    'travel.estimate_invoicing': 'Estimate Processing Cost (GH₵)',
    'travel.adults_count': 'Applicants (Adults)',
    'travel.children_count': 'Dependents (Minors)',
    'travel.start_date': 'Proposed Travel Date',
    'travel.upgrades': 'Required Official Documents & Add-ons',
    'travel.upgrade_canopy': 'Formal Invitation Letter Procurement (+GH₵ 500 per applicant)',
    'travel.upgrade_canopy_sub': 'Secured and verified invitation letter from Canada/host',
    'travel.upgrade_cocoa': 'Official Bank Draft Facilitation (+GH₵ 800 per applicant)',
    'travel.upgrade_cocoa_sub': 'Required bank drafts and financial statement validation',
    'travel.upgrade_crafts': 'Fast-Track Expedited Submission (+GH₵ 400 per applicant)',
    'travel.upgrade_crafts_sub': 'Priority vetting and direct portal uploads within 48 hours',
    'travel.sec_proposal_btn': 'Submit Visa Enquiry',
    'travel.booking_success': 'Visa Enquiry Logged Successfully!',
    'travel.booking_success_msg': 'Your travel/visa enquiry for {title} has been logged under NAY TRAVEL COMPANY. Total estimated fee is GH₵ {cost} GHS. Our specialists will contact you shortly.',
    'travel.board_voucher_msg': 'NAY Travel Company registration voucher logged',
    'travel.invoiced_total': 'ESTIMATED TOTAL: GH₵ {cost} GHS',
    'travel.save_package': 'Bookmark Package',
    'travel.rating': 'Success Rate: {score}/5.0',
    'travel.no_bookings': 'You have no active travel or visa enquiries logged yet.',
    
    // Footer
    'footer.para': 'Offinso Resident Private Connection Hub. Connecting citizens with digital agricultural Auctions, Jobs, specialized Literacy campaigns, relief lists, and eco-travel advisory planning.',
    'footer.header_services': 'Private Hub Services',
    'footer.header_resources': 'Citizen Resources',
    'footer.header_tourism': 'Eco-Tourism & Travel',
    'footer.about': 'About Our Private Hub',
    'footer.traditional': 'Offinso Traditional Council & Chiefs',
    'footer.bulletins': 'Local Hub Bulletins',
    'footer.tenders': 'Community Harvest Tenders',
    'footer.advisories': 'Offin River Safe Commutes',
    'footer.cocoa_sub': 'Cocoa Farmer Input Subsidy Portal',
    'footer.shea_coop': 'Women Shea Cooperative Standards',
    'footer.labor_rules': 'Ghana Labor Commission Standard Rules',
    'footer.kente_crafts': 'Ashanti Traditional Crafts Guild',
    'footer.livestock_farming': 'Smallholder Poultry & Layer Guides',
    'footer.monkey_sanctuary': 'Amanchia Monkey Sanctuary Guide',
    'footer.heritage_tour': "Offinso Chiefs Palace Tour Itineraries",
    'footer.forest_trekking': 'Offinso Forest Reserve Trekking Trails',
    'footer.transport': 'Trotro Station Schedules & Rates',
    'footer.pottery_workshops': 'Local Pottery & Beadmaking Workshops',
    'footer.copyright': '© 2026 OFFINSO PRIVATE CONNECTION HUB. All Rights Reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.authorization_seal': 'Licensed Resident Verification',
  },
  tw: {
    // Header & Navigation
    'nav.home': 'Mfiase Dwumadibea',
    'nav.municipality': 'Mpɔtam Nsɛm',
    'nav.municipality_menu': 'Mpɔtam Nsɛm Nhyehyɛeɛ',
    'nav.auction': 'Deals Page',
    'nav.events': 'Fekuo Nhyiam',
    'nav.health_safety': 'Apɔmuden ne Ahotɔ',
    'nav.jobs': 'Offinso Nnwuma pii',
    'nav.careers_menu': 'Offinso Nnwuma Nhyehyɛeɛ',
    'nav.literacy': 'Nkyerɛkyerɛ (Courses)',
    'nav.jobs_sub': 'Nnwuma pa a ɛwɔ hɔ',
    'nav.charity': 'Mmoa ne Nkosoɔ',
    'nav.relief_menu': 'Mmoa ne Nkosoɔ Nhyehyɛeɛ',
    'nav.all_programs_overview': 'Mmoa Dwumadi Nyinaa Okyerɛmu',
    'nav.agric_sector': 'Kua ne Mmoa Dwumadibea',
    'nav.social_dev': 'Ankorɛankorɛ Mpuntuo',
    'nav.travel': 'Akwantuo Abrokyire',
    'header.banner_left': 'Offinso Ankorɛankorɛ Nkabom, Ghana',
    'header.banner_right': 'Ashanti Mantam, West Africa',
    'header.seal_text': 'OFFINSO ANKOREANKORE',
    'header.bilingual_badge': 'EN / TWI',
    'header.title': 'OFFINSO ANKOREANKORE',
    'header.subtitle': 'Offinso Ankorɛankorɛ Dwumadibea',
    'header.search_placeholder': 'Hwehwɛ nnwuma, guaso, ne mmoa...',
    'header.river_status': 'Asuogya Offin Twasoɔ:',
    'header.river_passable': 'WOBƐTUMI ATWA',
    'header.weather': 'Offinso: 28°C Ɔhyɛ Mpɔtam',
    'header.hotline_prefix': '🔴 Offin Asuogya Kɔkɔbɔ: ',
    'header.warning_prefix': '⚡ Mpɔtam Nsɛm: Nsuo kɔkɔbɔ foforɔ biara nni hɔ',
    
    // Auth Buttons & Modal
    'auth.login': 'Wura Mu',
    'auth.signup': 'Kyerɛw Wo Din',
    'auth.logout': 'Pue Ara',
    'auth.welcome_user': 'Akwaaba, {name}',
    'auth.modal_title_login': 'Wura Resident Registry mu',
    'auth.modal_title_signup': 'Kyerɛw wo din sɛ Ɔmanba',
    'auth.username': 'Wo din (Email anaa Wo din)',
    'auth.password': 'Wo binn / Password',
    'auth.no_account': 'Wo nni resident account?',
    'auth.already_account': 'Woakyerɛw wo din dada?',
    'auth.security_question': 'Ɔmanba Dinhyɛ Asɛmmisa',
    'auth.security_placeholder': 'Mmuaeɛ na yɛde asiesie wo dodoɔ nyinaa...',
    'auth.secure_pet': 'Ɔman ba, hefa ne wo mmeranteberɛ kurom wɔ Offinso?',
    'auth.secure_parents': 'Ashanti kro bɛn so na wo awofoɔ hyiaeeɛ?',
    'auth.secure_school': 'Mfiasoɔ sukuu bɛn na wokɔɔyɛ wɔ Offinso?',
    'auth.secure_harvest': 'Adwumayɛ mu kɔkɔɔ nnuaba bɛn na wonyaa mfiaseɛ?',
    
    // Common / Global
    'global.explore': 'Hwɛ Mu',
    'global.apply_now': 'Bisa Dwumadi',
    'global.details': 'Nsɛm pii',
    'global.back': 'Sane Se',
    'global.submit': 'Hyɛ mu kɔ',
    'global.cancel': 'Gyae mu',
    'global.active': 'Dwumayɛ kɔ so',
    'global.currency': 'GH₵',
    
    // Home Hub Page
    'home.welcome_link': 'Offinso Private Nkabom',
    'home.akwaaba_title': 'Offinso Connection Man',
    'home.akwaaba_subtitle': 'Akwaaba — Atuu, Anya fɛrɛ kɔ hɔ Offinso Private Hub',
    'home.hero_para': 'Afe-na-afe, asase dɔte fɛfɛɛfɛ a aduaba kɔkɔɔ ne kwaeɛ bebree wɔ hɔ. Yɛboa adwumahwehwɛfoɔ ma wɔnya adwuma pa wɔ kɔkɔɔ ne shea butter dwumayɛ mu. Yɛasan nso boa ma ahiafoɔ nya private mmoa nkrataa. Yɛde abran adetɔ nso kyɛ nkosoɔ mma nkuroda ase nkorɔfoɔ a wonni bi.',
    'home.see_bulletins': 'Hwɛ Offinso Amanneɛbɔ',
    'home.join_registry': 'Kyerɛw wo din sɛ Ɔmanba',
    'home.municipal_services': 'Ankorɛankorɛ dwumadi & Mmoa dwumayɛ',
    'home.select_hub_office': 'PAW ANKORƐANKORƐ NKABOM DHUMADIBEA WƆ ASE HA',
    'home.bulletins_title': 'Offinso Amanneɛbɔ ne Local Nsɛm',
    'home.courses_title': 'Akenkan ne Atwerɛ Nkyerɛkyerɛ',
    'home.courses_subtitle': 'Nnkyerɛkyerɛ foforɔ, mfididwuma ne weba nkabom dwumadi fɛfɛɛfɛ.',
    'home.no_news': 'Nsɛm biara nni hɔ a ɛfa hwehwɛmu adiyisɛm yi ho.',
    'home.live_stats': 'Offinso Dwumadibea Nkrataa Din',
    'home.road_advisory': 'Asuogya Offin ne Akwan Kɔkɔbɔ',
    'home.road_para': 'Asuogya Offin twasoɔ lɔre ne kar nyinaa bɛtumi atwa sesei ara. Nsuo a ɛwɔ asubɔnten yi mu asesei pa ara adu Abofour mpɔtam. Akwan nyinaa anya awo, na ɛyɛ fɛ amamfoɔ akwantufoɔ kwan.',
    'home.eco_tour_teaser': 'Tutu akwan kɔ Amanchia Nwansena/Adɔeɛ Bea',
    'home.eco_tour_para': 'Tutu akwam fɛfɛɛfɛ fa mfiasoɔ kwaeɛ fɛfɛɛfɛ mu. Hwɛ kwakuo kuom pii wɔ wɔn taten bɛfɛfɛɛfɛ mu pɛpɛɛpɛ.',
    'home.eco_experience_label': 'Ecotourism Dwumadi fɛfɛɛfɛ',
    'home.pop_label': 'Ɔmanfoɔ Dodoɔ',
    'home.bids_label': 'Nguasodeɛ a Ɛkɔ so',
    'home.jobs_label': 'Nnwuma a Ɛda Hɔ / Woadi mu',
    'home.relief_label': 'Mmoa Sika a Yɛde Ama',
    
    // Benefactor Appreciation keys
    'home.appreciation_badge': 'NKRANHYƐ NE ASIDA MA BENEFACTOR PARTNER',
    'home.appreciation_title': 'Aseda Kɛseɛ Kɔ Haven Light Charity LBG Hɔ',
    'home.appreciation_desc': 'Yɛda Haven Light Charity LBG ase pii wɔ n’akrabɔ ne dɔ mmoa a afe-na-afe wɔde boa Offinso Amanfoɔ Mmoa ne Nkosoɔ Sika dwumadi no. Ɔnam wɔn nkabom ne sika dwumayɛ pa so, akuafoɔ, cooperatives afoforɔ, ne adwumayɛfoɔ pii anya seed subsidies, abura foforɔ, ne micro-grants sika a ɛbue kwan ma yɛn mpɔtin mu dwumadi. Yɛkabom a, na yɛbue Offinso fɛfɛɛfɛ.',
    'home.appreciation_twi': 'Aseda kɛseɛ kɔ Haven Light Charity LBG hɔ',
    
    // Auction Section
    'auction.floor_title': 'Community Nguasodeɛ Kurom',
    'auction.municipal_office': 'Offinso Private Nkabom Dwumadibea',
    'auction.floor_para': 'Nguasodeɛ a ɛdie abran afoforɔ pa, Kente shuttle ntadeɛ, ne Ashanti amanyɔsɛm adeɛ nyinaa fɛfɛɛfɛ. Bid mfiase kɔ a, ɛhia sɛ wonya GH₵5 kɔ akɔ.',
    'auction.stats_bidders': 'Adetɔfoɔ a wɔakyerɛw wɔn din:',
    'auction.lot_count': 'Nguasodeɛ afoforɔ a ɛda hɔ:',
    'auction.price_filter': 'Boɔ nkabom foforɔ:',
    'auction.min_bid_label': 'Boɔ kɛseɛ asuan (GH₵)',
    'auction.max_bid_label': 'Boɔ kɛseɛ aduam (GH₵)',
    'auction.bidder_prompt': 'Enterprise Buyer (Resident Account Hia)',
    'auction.become_bidder': 'Chyerew wo resident account ansa na woatumi ato boɔ.',
    'auction.bid_successful': 'Boɔ no akɔ yie fɛfɛɛfɛ!',
    'auction.bid_too_low': 'Wo boɔ no sua ara dodo. Sika a wobɛtumi ato no bɛfirii {min} (ehyem mpo no + {inc} increment hia).',
    'auction.ends_in': 'bɛto mu dwumadi {time} mu',
    'auction.starting_bid': 'Mfiaseɛ Boɔ',
    'auction.current_leading': 'Nea Ɔda mu Kan',
    'auction.no_bids': '0 bids dada',
    'auction.bids_count': '{count} bids nyinaa',
    'auction.is_high_bidder': 'Wone nea ɔda mu firi kɛseɛ mpo!',
    'auction.outbid': 'Nkorɔfoɔ asesa wo sika!',
    'auction.place_bid_btn': 'Hyɛ guaso boɔ foforɔ',
    'auction.rebid_btn': 'Sane fa sika foforɔ (GH₵ {amount}+)',
    'auction.submit_bid_btn': 'Pae Adetɔ boɔ pɛpɛɛpɛ',
    'auction.backing_rules_label': 'Nguaso Ahyɛdeɛ',
    'auction.backing_rules_text': 'Guaso sika biara a wobɛto wɔ ha yɛ ahyɛdeɛ mapa wɔ Offinso Amanneɛbɔ Nguasodeɛ mmra mma. Wobɛbɔ wo ho mmɔden abɛfa w’adeɛ wɔ Offinso Municipal Secretariat.',
    'auction.your_bid_amount': 'Wo Sika a Woto Guaso mu (GH₵)',
    'auction.min_increment_hint': 'Mfiase mmoa sika ɔhyia ne GH₵ 5. Ɛbɛyɛ GH₵ {amount} pɛpɛɛpɛ.',
    'auction.gold_weight': 'Tete Nneɛma anyansafoɔ',
    'auction.crafts': 'Ashanti Adwin',
    'auction.relics': 'Afuom-dwuma Relics',
    'auction.tools': 'Etuo-adwuma adadeɛ',
    'auction.utensils': 'Kukuo adwin pa',
    'auction.fine_arts': 'Adwin fɛfɛɛfɛ',

    // Job Search Section
    'jobs.portal_title': 'Amansin Nnwuma Kyɛfa Ledger',
    'jobs.sub_office': 'Mmeranteberɛ ne Adwumayɛbea Dwumadibea',
    'jobs.portal_para': 'Mmoa a yɛde ma amamfoɔ adwumahwehwɛfoɔ ma wɔnya adwuma pa wɔ kɔkɔɔ mfiasoɔ mu, shea butter cooperations, ne kwaeɛ nkosoɔ mu.',
    'jobs.tab_listings': 'Hwehwɛ Nnwuma',
    'jobs.tab_applications': 'Resident Nkrataa',
    'jobs.tab_post': 'Pae Adwuma Foforɔ',
    'jobs.search_title': 'Hwehwɛ Nnwuma pii',
    'jobs.select_category': 'Paw Adwuma mu Su',
    'jobs.select_type': 'Adwuma mmere',
    'jobs.salary_label': 'Adwuma Akatua / Bosome',
    'jobs.all_categories': 'Dwumayɛ mu nyinaa',
    'jobs.salary_limit_label': 'Bosom Akatua a eye kɛseɛ',
    'jobs.post_vacancy_title': 'Pae Adwumayɛ foforɔ wɔ mpɔtam',
    'jobs.post_vacancy_para': 'Kyɛ adwuma a wobɛtumi de ama Offinso amamfoɔ atwa mboa a yɛbɛyɛ de apopa hia firi mpɔtam. Adwuma biara bɛkɔ validation mu.',
    'jobs.form_title': 'Adwuma no Titen',
    'jobs.form_employer': 'Employer Din anaa Cooperative',
    'jobs.form_location': 'Local Community (sɛ Anyinasuso, Abofour)',
    'jobs.form_salary': 'Akatua ɔbɛbɔ (GH₵)',
    'jobs.form_desc': 'Okyerɛmu fa adwumayɛ no ho',
    'jobs.form_req': 'Adwuma hwehwɛdeɛ (Fa mmiako-mmiako hyɛ line foforɔ biara so)',
    'jobs.create_post_btn': 'Sɔ Hwɛ na Pae Adwuma no',
    'jobs.candidate_apply_title': 'Bisa saa adwumayɛ yi',
    'jobs.apply_fullName': 'Wo din mapa kuraa',
    'jobs.apply_phone': 'MoMo Telefoono Nɔma fɛfɛɛfɛ',
    'jobs.apply_experience': 'Adwumayɛ mmerɛ weɛ ne nimdeɛ a wowɔ',
    'jobs.apply_narrative': 'Okyerɛmu mfiase',
    'jobs.apply_narrative_placeholder': 'Ɛfiri deɛn nti na wone ɔmanba mapa a wobɛtumi atwa adwuma yi de aboaduru hia...',
    'jobs.apply_success': 'Wo Application Krataa no kɔɔ yie pa ara!',
    'jobs.tracker_code': 'Wo tracker reference nɔma ne:',
    'jobs.requirements': 'Adwumayɛ hwehwɛdeɛ',
    'jobs.your_applications': 'Wo Application Nkrataa nyinaa',
    'jobs.no_applications': 'Wonnyaa Bisaa adwumayɛ krataa biara.',
    'jobs.applied_on': 'Bisaeɛ da {date}',
    'jobs.status': 'Mmerɛ: {status}',
    'jobs.verified_status': 'Ɔmanba mapa a yɛahu no',
    
    // Charity Section
    'charity.alliance_title': 'Amanfoɔ Mmoa ne Nkosoɔ Sika',
    'charity.sub_office': 'Haven Light Charity LBG',
    'charity.alliance_para': 'Adiyisɛm pa a yɛde twa asase kɔkɔbɔ afuom nkosoɔ, ne sika nkɔsoɔ maa hiafoɔ abusua nyinaa wɔ Offinso amansin mu. Haven Light Charity LBG na ɛhwɛ so.',
    'charity.tab_programs': 'Mmoa Sika Dwumadi',
    'charity.tab_apply': 'File Relief Bisa-mmoa',
    'charity.tab_track': 'Mu Tracker foforɔ',
    'charity.empowering': 'Empowering Local Communities',
    'charity.empowering_text': 'Haven Light Charity LBG de nguasodeɛ sika 15% nyinaa kɔ seed subsidies, abura foforɔ tutu dwuma mu, ne mmaa groups mu.',
    'charity.required_dossiers': 'Nkrataa ɔhia ma application',
    'charity.required_dossiers_text': 'Ampa ara, wo bisa mmoa a, ɛhia sɛ wonya resident krataa firi Offinso amansin mu, wo bosome sika, ne asɛm okyerɛmu a ɛfa wo ho.',
    'charity.fund_pool': 'Sika dodoɔ a yɛde ama mfe yi:',
    'charity.claim_title': 'File Relief Bisa-mmoa foforɔ',
    'charity.claim_para': 'Bisa mmoa sika firi nkosoɔ dwumadi mu. Sika a yɛbɛgye atom no bɛba Mobile Money (MoMo) so kɛse.',
    'charity.claim_success': 'Bisa-mmoa no anya Resident Registry foforɔ!',
    'charity.claim_ref': 'Reference Tracker Nɔma',
    'charity.claim_success_msg': 'Wo bisa mmoa no akɔ dwumadibea krataa mu. Sane kura wo reference tracker code yi yie: {ref}',
    'charity.form_program': 'Paw mmoa dwumayɛ sika bɛn',
    'charity.form_program_placeholder': '-- Paw specialized program --',
    'charity.form_income': 'Wo Bosome Gross Income Nkabom',
    'charity.form_desc': 'Okyerɛmu adiyisɛm pɛpɛɛpɛ fa mmoa ɔpɛ ho',
    'charity.submit_claim_btn': 'Pau na gye Bisa-mmoa atom',
    'charity.track_title': 'Bisa-mmoa Tracker Ledger',
    'charity.track_para': 'Hwehwɛ mmoa sika app mmerɛ so fa wo email anaa wo tracker nɔma pɛpɛɛpɛ.',
    'charity.track_btn': 'Hwehwɛ Tracker mmerɛ',
    'charity.track_query_placeholder': 'sɛ kofi@offinso.com anaa OFS-RLF-189',
    'charity.no_records': 'Yɛnnya mmoa krataa biara a kura {query}.',
    'charity.status_label': 'Din mmerɛ mu nsɛm',
    
    // Travel Section
    'travel.agency_title': 'NAY TRAVEL COMPANY',
    'travel.sub_office': 'Amanɔne Akwantuo ne Visa Dwumadibea',
    'travel.agency_para': 'Akwantuo dwumadi nyinaa yɛ deɛ NAY TRAVEL COMPANY de ma. Yɛyɛ visa krataa, sika krataa (bank draft), ne invitation krataa fɛfɛɛfɛ.',
    'travel.tab_packages': 'Hwɛ Akwantuo Nsɛm',
    'travel.tab_my_trips': 'M’abisa-mmoa nyinaa',
    'travel.calculator_title': 'Akwantuo sika calculator',
    'travel.calc_directions': 'Paw akwantuo dwumadi bi wɔ benkum so ansa na woatumi de wo bisa-mmoa akɔ.',
    'travel.destination_label': 'Ɔman a wo kɔ',
    'travel.destination_placeholder': 'sɛ Canada, UK, Europe',
    'travel.max_price': 'Sika dodoɔ bar (GH₵ {price} GHS)',
    'travel.price_range': 'Asua kɛse: GH₵ 100 | Edu kɛse: GH₵ 10000 GHS',
    'travel.base_rate': 'PROCESSING FEE',
    'travel.per_person': '/onipa biara',
    'travel.estimate_invoicing': 'Akwantuo sika dodoɔ (GH₵)',
    'travel.adults_count': 'Akwantufoɔ atitire (Adults)',
    'travel.children_count': 'Mmofra / Ngwa',
    'travel.start_date': 'Proposed Travel Date',
    'travel.upgrades': 'Required Krataa ne Add-ons',
    'travel.upgrade_canopy': 'Invitation Letter Procurement (+GH₵ 500 onipa biara)',
    'travel.upgrade_canopy_sub': 'Formal invitation krataa a ɛfiri ɔman no mu',
    'travel.upgrade_cocoa': 'Official Bank Draft Facilitation (+GH₵ 800 onipa biara)',
    'travel.upgrade_cocoa_sub': 'Sika krataa ne bank statements verification',
    'travel.upgrade_crafts': 'Fast-Track Priority Processing (+GH₵ 400 onipa biara)',
    'travel.upgrade_crafts_sub': 'Priority check-in ne direct uploads ntɛmtem',
    'travel.sec_proposal_btn': 'De Bisa-mmoa kɔ',
    'travel.booking_success': 'Bisa-mmoa akɔ NAY TRAVEL dwumadibea!',
    'travel.booking_success_msg': 'Wo bisa-mmoa ama {title} akɔ ledger mu wɔ NAY TRAVEL COMPANY. Sika dodoɔ ne GH₵ {cost} GHS. Akwantuo kyɛfo bɛbɔ wo phone sesei.',
    'travel.board_voucher_msg': 'NAY Travel voucher na woapae',
    'travel.invoiced_total': 'ESTIMATED TOTAL: GH₵ {cost} GHS',
    'travel.save_package': 'Bookmark hyea',
    'travel.rating': 'Anigyeɛ: {score}',
    'travel.no_bookings': 'Wonnyaa kyerɛw bisa-mmoa biara.',
    
    // Footer
    'footer.para': 'Dwumadi a ɛdi boa Offinso Amansin mu Ashanti Mantam amamfoɔ. Yɛkabom amamfoɔ sika kɔ adwin nguaso, nnwuma, bisa-mmoa, ne eco-tourism akwantuo mu.',
    'footer.header_services': 'Amanne dwumadi',
    'footer.header_resources': 'Ɔmanba Mmoa',
    'footer.header_tourism': 'Eco-Tourism & Akwantuo',
    'footer.about': 'Offinso Amansin mu Nsɛm',
    'footer.traditional': 'Offinso Traditional Council & Chiefs',
    'footer.bulletins': 'Municipal Bulletins',
    'footer.tenders': 'Community Harvest Tenders',
    'footer.advisories': 'Offin River Flood Advisories',
    'footer.cocoa_sub': 'Cocoa Farmer Input Subsidy Portal',
    'footer.shea_coop': 'Women Shea Cooperative Standards',
    'footer.labor_rules': 'Ghana Labor Commission Standard Rules',
    'footer.kente_crafts': 'Ashanti Traditional Crafts Guild',
    'footer.livestock_farming': 'Smallholder Poultry & Layer Guides',
    'footer.monkey_sanctuary': 'Amanchia Monkey Sanctuary Guide',
    'footer.heritage_tour': "Offinso Chiefs Palace Tour Itineraries",
    'footer.forest_trekking': 'Offinso Forest Reserve Trekking Trails',
    'footer.transport': 'Trotro Station Schedules & Rates',
    'footer.pottery_workshops': 'Local Pottery & Beadmaking Workshops',
    'footer.copyright': '© 2026 OFFINSO NKABOM. All Rights Reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.authorization_seal': 'Municipal Code Authorized Seal',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('offinso_language');
    return (saved === 'tw' || saved === 'en') ? (saved as Language) : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('offinso_language', lang);
  };

  const t = (key: string, fallback?: string, variables?: Record<string, string | number>): string => {
    let text = dictionary[language]?.[key] || fallback || key;

    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
